### ISSUE TITLE
Install error: raw_decode: ValueError: Expecting property name enclosed in double quotes

### ISSUE THREAD

**Issue by Un1Gfn** [adamchainz/rst-improved#4]
Installation failure

Sublime Text, Stable Channel, Build 4113

Get the following message with <kbd>Ctrl+`</kbd>

<details><summary>(1) Right before the error</summary>

```
Package Control: Urllib HTTPS Debug Read
  HTTP/1.1 200 OK
  Server: nginx
  Date: Tue, 27 Jul 2021 11:12:13 GMT
  Content-Type: application/json
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  X-App-Version: 1.7.0
  Strict-Transport-Security: max-age=15552000
  Content-Encoding: gzip
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading python 3.3 plugin RestructuredText Improved.RestructuredText Improved
user_preferences_file: /home/darren/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
s: {
  "color_scheme": "Packages/Color Scheme - Default/Monokai.sublime-color-scheme", // 10
  "font_face": "DejaVu Sans Mono", // 20
  "font_size": 12, // 21
  "font_options": // 48
  [
    "gray_antialias",
    "subpixel_antialias"
  ],
  "word_separators": "./\\()\"'-:,.;<>~!@#$%^&*|+=[]{}`~?", // 54
  "mini_diff": false, // 75
  "tab_size": 2, // 84
  "translate_tabs_to_spaces": true, // 87
  "auto_indent": true, // 97
  "word_wrap": false, // 114
  "auto_complete": false, // 370
  "copy_with_empty_selection": false, // 477
  "drag_text": false, // 505
  "theme": "Default.sublime-theme", // 515
  "ignored_packages": ["Vintage",
  ], // 798
}
```

</details>

**(2) The error**

```
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 400, in load_module
    m.plugin_loaded()
  File "/home/darren/.config/sublime-text-3/Installed Packages/RestructuredText Improved.sublime-package/RestructuredText Improved.py", line 63, in plugin_loaded
    user_preferences = json.loads(s)
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 367, in raw_decode
ValueError: Expecting property name enclosed in double quotes: line 2 column 82 (char 83)
```
<details><summary>(3) Right after the error</summary>

```
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
generating meta info summary
generating syntax summary
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Urllib HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request
```

</details>

PS: IDK where to find `decoder.py`. If it is needed please tell me how to get it.

Appreciated.

**Comment by adamchainz** [comment]
Hi

I only uploaded the existing package. I think it crashes with extended JSON in your settings file. The "edit your settings file" function could be removed from this package.
